version: '2.4'

services:
  backend:
    image: node:12
    command: bash -c "yarn install && yarn start:dev"
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3001:3001
    networks:
      - backend_network

  es01:
    image: elasticsearch:7.10.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backend_network

  kib01:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    networks:
      - backend_network

volumes:
  data01:
    driver: local

networks:
  backend_network:
    driver: bridge
